# MySQL datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/instructor_course
    username: instructor_course
    password: instructor_course

# Logging level : warn
logging:
  level:
    root: warn